######################################################################
# Automatically generated by qmake (2.01a) pon. wrz 17 09:04:01 2012
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += qt-Debug.pro qt-Release.pro
